- name: Configure the nginx document root folderin Centos
  when: (ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
  copy: src=default.conf dest=/etc/nginx/conf.d/default.conf backup=yes