- name: This playbook will provision couple of ubuntu and centos containers
  hosts: localhost
  vars:
    proxy_configuration:
      http_proxy: http://10.20.30.40:8080
      https_proxy: https://10.20.30.40:8080

    platform_dictionary:
      ubuntu:
        image: "verizon/ansible-ubuntu"
        dockerfile: "UbuntuDockerfile"
      centos:
        image: "verizon/ansible-centos"
        dockerfile: "CentOSDockerfile"

    docker_images:
     - "verizon/ansible-ubuntu"
     - "verizon/ansible-centos"

    
  tasks:
    - name: Install Extra packages for Enterprise Linux(EPEL)
      when: ansible_distribution == "CentOS"
      yum: name=epel-release state=latest

    - name: Install Python package installer utility
      when: ansible_distribution == "CentOS"
      yum: name=python-pip state=latest
    
    - name: Install Python package installer utility
      when: ansible_distribution == "Ubuntu"
      apt: name=python-pip state=latest update_cache=yes
    
    - name: Install docker.py python package
      shell: pip install docker-py

    - name: Delete all containers if running previously
      shell: "docker rm -f $(docker ps -aq)"
      ignore_errors: yes
      

    - name: Delete all images if running previously
      shell: "docker rmi -f {{item}}"
      ignore_errors: yes
      with_items: "{{docker_images}}"
      
    - name: Build ansible Ubuntu and CentOS images
      docker_image:
          name: "{{item.value.image}}"
          state: build
          path: .
          dockerfile: "{{item.value.dockerfile}}"
      with_dict: "{{platform_dictionary}}"

    #- name: Build ansible Centos images
     # docker_image:
      #    name: "verizon/ansible-centos"
       #   state: build
        #  path: .
         # dockerfile: "CentOSDockerfile"